name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can change this to the required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asyncio websockets

    - name: Download and run Python script
      run: |
        curl -O https://raw.githubusercontent.com/Nodiddybuttttt/mypythoncode/refs/heads/main/main.py
        python main.py
